apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep-ex
  labels: 
    app: myapp
    type: front-end


spec:
  replicas: 2
  selector: 
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine

