apiVersion: v1
kind: Service
metadata:
  name: service-app

spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30001 # range 30000 to 32767
  selector:
    app: myapp
    type: front-end

# minikube service service-app --url
