apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep-ex
  labels: 
    app: myapp
    type: front-end


spec:
  replicas: 2
  selector: 
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine

# kubectl create -f x.yml
# kubectl get replicaset
# kubectl delete replicaset rep-ex
# kubectl scale --replicas=n -f x.yml (without modifing)
# kubectl replace -f x.yml (modifing the config file)