apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replication-app
  labels: 
    app: myapp


spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:alpine

# kubectl create -f x.yml
# kubectl get replicaset
# kubectl delete replicaset rep-ex
# kubectl scale --replicas=n -f x.yml (without modifing)
# kubectl replace -f x.yml (modifing the config file) 
# kubectl scale replicaset replication-app --replicas=2
# kubectl edit replicaset replication-app --replicas=2