apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replication-app
  labels:
    app: myapp
spec: 
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-alpine
          image: nginx:alpine